openapi: 3.0.0
info:
  title: TO-DO APPLICATION
  version: 1.0.0
  description: documentation for Todo API
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt

paths:
  /api/courses/signup:
    post:
      summary: sign up new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Enter you name please
                email:
                  type: string
                  example: Enter your email please
                password:
                  type: string
                  example: Enter your new password please
      responses:
        200:
          description: User created succussfully
          content:
            application/json:
              schema:
                type: object

  /api/courses/login:
    post:
      summary: user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Arian
                password:
                  type: string
                  example: test
      responses:
        200:
          description: user logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  name:
                    type: string
                  accesstoken:
                    type: string
                  refreshtoken:
                    type: string
          400:
            description: login failed
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string

  /api/courses/update_user:
    put:
      summary: update user info
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Enter the field you want to change:
                  type: string
                  example: Enter it's value
      responses:
        200:
          description: User info updated succussfully
          content:
            application/json:
              schema:
                type: object

  /api/courses/delete_user:
    delete:
      summary: Delete user
      security:
        - bearerAuth: []
      responses:
        200:
          description: User deleted succussfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/courses/register_course:
    post:
      summary: Register new course
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            enum: [python, javascript, C#]
          description: Enter course name
        - in: query
          name: duration
          required: true
          schema:
            type: string
            enum: [10H, 50H, 100H, 150H]
          description: Select your course duration
        - in: query
          name: time
          required: true
          schema:
            type: string
            enum: [9:00-12:00, 12:00-15:00, 15:00-18:00, 18:00-21:00]
          description: Select course time
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: [not started, in progress, completed]
          description: Select your course status
      responses:
        200:
          description: course registered succussfully
          content:
            application/json:
              schema:
                type: object

  /api/courses/update_course/{course_name}:
    put:
      summary: update course information
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: course_name
          required: true
          schema:
            type: string
            enum: [python, javascript, C#]
            default: Enter course name
          description: course name
        - in: query
          name: time
          required: true
          schema:
            type: string
            enum: [9:00-12:00, 12:00-15:00, 15:00-18:00, 18:00-21:00]
            default: Enter course time
          description: course time
        - in: query
          name: duration
          required: true
          schema:
            type: string
            enum: [10H, 50H, 100H, 150H]
            default: Enter course duration
          description: course duration
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: [not started, in progress, completed]
            default: Enter course status
          description: course status
      responses:
        200:
          description: Course updated succussfully
          content:
            application/json:
              schema:
                type: string

  /api/courses/delete_course:
    delete:
      summary: Delete course
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: course_name
          required: true
          schema:
            type: string
            enum: [python, javascript, C#]
          description: Select a course to delete
      responses:
        200:
          description: Course deleted succussfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Course deleted succussfully

  /api/courses/showDB:
    get:
      summary: show database
      content:
        application/json:
          schema:
            type: object
      responses:
        200:
          description: database showed succussfully
          content:
            application/json:
              schema:
                type: object

  /api/courses/access_token:
    get:
      summary: Get new accesstoken
      security:
        - bearerAuth: []
      responses:
        200:
          description: New accesstoken
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: sklfvnfsjkvnjkfbjfkdb
